ORTHANC_IP = 'orthanc'
ORTHANC_HOST = 'orthanc'
ORTHANC_PORT = 4242
ORTHANC_AET = 'ORTHANC'
CLIENT_AE_TITLE = 'CLIENT_AE'
ORTHANC_AE_TITLE = "ORTHANC"
CLIENT_PORT = 11112
CLIENT_AE_TITLE = ""


DICOM_DIR = '/app/data/uploads'
STORAGE_DIR = '/app/DICOM/storage/'


